apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: app-pipeline
description: Application delivery pipeline
serialPipeline:
  stages:
  - targetId: dev-target
    profiles: [dev]
  - targetId: prod-target
    profiles: [prod]
    strategy:
      standard:
        verify: true

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-target
description: Development deployment target
run:
  location: ${_REGION}

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-target
description: Production deployment target
run:
  location: ${_REGION}
requireApproval: true